### ISSUE TITLE
missing LUKS password input

### ISSUE THREAD

**Issue by ThomasCr** [emanuele-scarsella/vortex-ubuntu-plymouth-theme#4]
Hi, i tested your nice theme today, but unluckily it is not asking me for the LUKS password.

**Comment by smkent** [comment]
@ThomasCr I've implemented password prompt in this PR: https://github.com/emanuele-scarsella/vortex-ubuntu-plymouth-theme/pull/5

**Comment by emanuele-scarsella** [comment]
@smkent PR has been pushed and now LUKS password prompt has been implemented.
